### ISSUE TITLE
Only works on source.jq

### ISSUE THREAD

**Issue by bgha-stibosystems** [zogwarg/SublimeJQ#1]
The syntax highlighting only works for me if the file is source.jq, not when it is any other file name ending in .jq. My subl version is 3.0 build 3143.

**Comment by zogwarg** [comment]
Yes, that is because of the way file syntax detection works in sublime.

I recommend using [ApplySyntax](https://packagecontrol.io/packages/ApplySyntax) with this setting:

```json
{
    "syntax": "JQ Syntax/JQ",
    "extensions": ["jq"],
    "rules": [
        {"file_path": ".*(\\\\|/).jq$"}
    ]
}
```

The rule section makes it check for the exact filename ".jq"

**Comment by zogwarg** [comment]
I'll Add an FAQ section, and close the issue later

**Comment by zogwarg** [comment]
Ahh sorry, didn't fully understand the issue. Does Apply syntax still fix it ?

**Comment by bgha-stibosystems** [comment]
Thank you.
